output:
  formats: line-number

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - goheader
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  goimports:
    local-prefixes: "github.com/otto-de/traefik-config-validator"
  goheader:
    template-path: hack/boilerplate.go.txt
    values:
      const:
        AUTHOR: OTTO GmbH & Co KG
